modLoader="javafml"
loaderVersion="[38,)"
license="CC BY-NC-SA 4.0"

[[mods]]
modId="jade"
version="${file.jarVersion}"
displayName="Jade"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/jade"
description="HWYLA fork & addons"

[[mods]]
modId="waila"
version="${file.jarVersion}"
displayName="Waila (Jade)"
authors="Snownee, TehNut, ProfMobius"
description="You are using Jade, a fork of Hwyla."


[[dependencies.jade]]
    modId="forge"
    mandatory=true
    versionRange="[38, )"
    ordering="NONE"
    side="BOTH"

[[dependencies.jade]]
    modId="jei"
    mandatory=false
    versionRange="[9.7, )"
    ordering="NONE"
    side="BOTH"

[modproperties.jade]
    catalogueItemIcon="minecraft:spyglass" #Support for Catalogue mod
