modLoader = "javafml"
loaderVersion = "[1,)"
license = "CC-BY-NC-SA-4.0"

[[mods]]
modId = "jade"
version = "${file.jarVersion}"
displayName = "Jade"
authors = "Snownee"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/jade"
description = "Minecraft mod shows what you are looking at. (Hwyla fork)"
logoFile = "icon.png"
credits = "TehNut, ProfMobius, kalkafox"

[[mixins]]
config = "jade.mixins.json"

[[dependencies.jade]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.11-beta, )"
ordering = "NONE"
side = "BOTH"
